---
tenant:
  url: "https://essensys-us.analytics.accedian.io"
  username: "dpearce@accedian.com"
  pvql query: "ct.count BY flatten(client.zone.name, 3) FROM tcp SINCE @(2023-07-17T00:00:00.000Z) UNTIL @(2023-07-26T23:59:59.000Z)"
  output file: "extract_sizing_sites_uk.csv"
