---
tenant:
  url: "https://essensys-us.analytics.accedian.io"
  username: "dpearce@accedian.com"
  pvql query: "#client.zone.id BY flatten(client.zone.id, 2) FROM transport WHERE (client.zone.id NOT IN 2 AND client.zone.id NOT IN 6) SINCE @(2023-07-06T00:00:00.000Z) UNTIL @(2023-07-06T23:59:59.000Z)"
  output file: "extract_sizing.csv"
