---
tenant:
  url: "https://essensys-us.analytics.accedian.io"
  username: "dpearce@accedian.com"
  pvql query : 'server.rt,traffic BY application.name FROM tls TOP 3600'
  output file: 'extract.csv'
...