---
tenant:
  url: "https://essensys-us.analytics.accedian.io"
  username: "dpearce@accedian.com"
  pvql query: "ct.count BY server_name FROM tls SINCE @(2023-03-01T00:00:00) UNTIL @(2023-03-01T23:59:00)"
  output file: "extract_us.csv"
